### ISSUE TITLE
Error Can't Find CustomizableTowerClass [Working on it]

### ISSUE THREAD

**Issue by PoisonArrow1000** [DarkTerraYT/CustomizableTower#3]
When I load up the game and go to mods it is telling me that it can't find the class for the tower and when I load up a game it doesn't show the tower to place.

**Comment by buttonmash147** [comment]
Same here

**Comment by buttonmash147** [comment]
It could be because your tower has different projectile types checked, but that's not the case for me.

**Comment by DarkTerraYT** [comment]
Which weapons did you use? Some of them might be broken and I didn't test them all.

**Comment by buttonmash147** [comment]
I used rockets.

**Comment by DarkTerraYT** [comment]
Okay try to not use any projectile that doesn't work

**Comment by DarkTerraYT** [comment]
It was because of a typo I fixed this a while ago
